### ISSUE TITLE
accumulate: Readme doesn't match the tests.

### ISSUE THREAD

**Issue by zeimusu** [exercism/go#1070]
The Readme for accumulate uses an example of a numeric list, but the test cases all use strings. The Readme should be rewritten. 

----
Given the collection of strings:

    "the", "cat", "sat", "on", "the", "mat"

And the operation:

`Capitalise` a string (`"cat" => "CAT"`)

Your code should be able to produce the collection of words:

    "THE", "CAT", "SAT", "ON", "THE", "MAT"
----

**Comment by tleen** [comment]
@zeimusu excellent observation. Sorry I missed this one last week! Since this exercise has [no canonical test cases over at problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/accumulate) we can modify the README as we see fit. 

Would you like to submit a PR to fix the README? We should probably [add a .meta/  directory](https://github.com/exercism/go#exercism-go-style) and handle it there...

**Comment by ooransoy** [comment]
Hello, I made a few edits to the README to fix this issue. I closed the first PR and created a second one because I messed up the Git structure or something like that.
