### ISSUE TITLE
space-age requires a type declaration and maybe shouldn't, or the hint should be exposed.

### ISSUE THREAD

**Issue by bensherman** [exercism/go#1239]
I did space-age today and I couldn't quite figure out what to do with the type errors I got, because we haven't been defining types yet.

```
./cases_test.go:9:14: undefined: Planet
```

I went and checked out the line at that file, and then thought it may be an error in the test file. I changed the `Planet` type to a `string` and everything worked. I came here to open an issue and found that not only was it intentional, it was talked about in a recent commit to the repo (https://github.com/exercism/go/pull/1236). The issue was opened with the same question I had.

As I am new to exercism, I think this might be a tad too early to make someone define a type. If that's not the case and this is how it is meant to be, the hint in the above mentioned commit is a good one. However, I could not figure out where that hint was supposed to be exposed - I never saw it.

Am I doing something wrong regarding hints and is there a better time to introduce a new type definition requirement?

What do you think @BigChief45 and @bitfield?

**Comment by bitfield** [comment]
I completely understand what you're saying. However, if you're learning Go it's _super important_ to be able to define types. It's something you do a lot, even if, as here, it's a more or less trivial type which is more documentation than anything else.

There are exercises on the core track where you define more advanced types (Tournament, Bank Account, and so on). But we have to _introduce_ the idea at some point. Here seems as good as anywhere.

I agree that it's a bit much to expect that people will figure out by themselves from test failures that they need to implement a type, and how to do that. The PR you mention fills that gap nicely, I think, by explaining what's needed, and more or less telling you what to do to achieve it.

The reason that hint's not showing up is, I think, because the PR only touched the metadata file, without updating the README that's generated from it automatically. I may be wrong, but I think doing this will be sufficient to update it:

```
./bin/fetch-configlet
./bin/configlet generate . --only space-age
```

**Comment by bensherman** [comment]
Thanks for the input!

This is simply a technical problem with the check-in of the hint, consider this an issue to fix it! 

PR is incoming, thanks for the quick response.
