### ISSUE TITLE
linked-list: naive implementation leads to endless loop during test

### ISSUE THREAD

**Issue by voelzmo** [exercism/go#1255]
Hi,

here is what I started out with for the linked-list exercise: https://gist.github.com/voelzmo/57b9f35ce43ebf06f4ef68b25b89291f

With this, an execution of `go test -v .` never returns. I started even smaller with `First()` returning `nil` and then `&Element{}`, ending up at `&Element{1}`. Then I added `&Element{}` as return to `Next()`, and the tests never returned back. This is the only output I get
```
$ go test -v .
=== RUN   TestNew
=== RUN   TestNew/from_5_elements
```

Ideally, I could start out small and have the tests guide me towards a solution, this doesn't seem to work well here.

**Comment by brugnara** [comment]
Hi @voelzmo.

Working with lists is always fun.

I would say the biggest problem in your implementation, is the way your `Next()` always returns something.

One would iterate a list, doing:

```
for list.Next() != nil {
    // some magic here
    list = list.Next()
}
```

And this is the case, so since Next() will never be nil, an infinite loop will occur.

But I see your point. For a student is more useful to be aware that a loop occurred than having the computer freezed.

Maybe you will find the [timeout](https://golang.org/cmd/go/#hdr-Testing_flags) useful when executing tests:

```
go test -v -timeout 5s .
```

Thanks a milion.

**Comment by voelzmo** [comment]
Thanks for getting back to this issue, I really appreciate the thoughtful feedback! Maybe I'm too used to TDD and therefore was assuming this should be an approach that works with this exercise as well: Just write the minimal amount of code that makes the first red test to be green, move on to next red test. In many exercism tasks, this isn't really possible as most of the time there's a single big test case, checking all conditions and real big "flows".

I'm happy to see that your PR is able to detect a loop and that it will give people a good hint towards what's happening in their implementation. Where I'm coming from, this would be a separate test case probably, but I see that your current approach is very much in line with the way the tests are currently designed.

**Comment by brugnara** [comment]
@voelzmo your approach is good. I could only recommend you to use `nil` next time, instead of "random" instances 😬 🍺  

Thanks
