### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/go#1265]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by leenipper** [comment]
For exercises currently without stubs, I'm thinking that providing a one line stub file which has the correct "package name" line matching the package name in the _test.go file is reasonable.

There are two README.md files (exercises raindrops and space-age) which need the '# No Stub' section replaced/reworded, since the stub file will be there, but with less content than prior exercises in the track.  The .meta/hints.md file is the source of the '# No Stub' section, so edit the .meta/hints.md and re-run configlet to re-generate the README.md for the exercise, as in
```
./bin/fetch-configlet
./bin/configlet generate $PWD --only space-age
``` 

There is no need to provide stub files for the deprecated exercises (binary, counter, hexadecimal, octal and trinary); the config.json has these marked ```"deprecated": true```.

The stub file name must match the exercise directory name, except replace any dash(-) with underline(_) in the stub file name.

Inside each new stub file, place one line with
```package name```
where ```name``` matches the package name in the *_test.go file.

Unless I missed something, that's it.

**Comment by kytrinyx** [comment]
I think this sounds like an excellent plan!
