### ISSUE TITLE
robot-name: benchmark is impossible on fast machine and/or efficient algoritm

### ISSUE THREAD

**Issue by wederbrand** [exercism/go#1355]
There is a total of 676_000 tests that can be made during one invokation (if you also solve the bonus tests). 
The benchmarking on my machine runs with b.N = 1, 100, 10_000, 1_000_000 iterations which will be too much.

**Comment by tehsphinx** [comment]
@bitfield: Any thoughts on this?

**Comment by bitfield** [comment]
There is a comment on the benchmark code that warns you about this:

```go
// Note if you go for bonus points, this benchmark likely won't be
// meaningful.  Bonus thought exercise, why won't it be meaningful?
func BenchmarkName(b *testing.B) {
```

Actually, I like the fact that this happens, because it usually stimulates an interesting conversation about how the benchmarker works. We could add instructions for students to avoid the issue by running:

```
go test -bench=.  -benchtime=676000x
```

but I think that would be a shame, because then we wouldn't have the conversation!

**Comment by tehsphinx** [comment]
@wederbrand: any thoughts on this or can we close it?

**Comment by wederbrand** [comment]
I'm fine with closing it but I don't fully agree. 

Perhaps the problem is with the entire bonus-tests. They will force another solution and another optimization. The bonus part was the best part but my final solution was for the "normal" tests and non-optimal solution.

And the discussion was around memory usage which is hard, or impossible, to test for the bonus-part with the current setup.
