### ISSUE TITLE
Matrix constructor shall return a pointer of Matrix?

### ISSUE THREAD

**Issue by stt106** [exercism/go#1438]
https://github.com/exercism/go/blob/64d5dd0799d4fbbc26dfea6440e0c1029528fa4c/exercises/practice/matrix/matrix_test.go#L6

The constructor shall return a pointer of `Matrix` otherwise it can't be compared to `nil`. 
In my download of the exercise, it does mention it expects a pointer instance from `New`, however, in the `BenchmarkNew`, it creates a variable of type `Matrix`, if the constructor does need to return a pointer, it shall create the variable of type `*Matrix` instead.

**Comment by tehsphinx** [comment]
Can you show where it mentions, that it "shall return a pointer for `Matrix` otherwise it can't be compared to `nil`."

Matrix is defined as `type Matrix [][]int` in the example implementation, so no pointer is needed as a slice can be `nil` and be compared to `nil`. (Example implementation is in the `matrix/.meta/` subfolder)

**Comment by stt106** [comment]
sorry my mistake, I misunderstood the exercise requirement.
