### ISSUE TITLE
concept exercises: go.mod is missing

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/go#1490]
When I download a concept exercise the file `go.mod` is missing.

```
$ exercism download --exercise=annalyns-infiltration --track=go

Downloaded to
/home/user/exercism/go/annalyns-infiltration

$ tree annalyns-infiltration
annalyns-infiltration
├── annalyns_infiltration.go
├── annalyns_infiltration_test.go
├── HELP.md
├── HINTS.md
└── README.md

0 directories, 5 files
```

But when I download a practice exercise, that file is present and I can start solving.
```
$ exercism download --exercise=tree-building --track=go

Downloaded to
/home/user/exercism/go/tree-building

$ tree tree-building
tree-building
├── go.mod
├── HELP.md
├── README.md
├── tree_building.go
└── tree_building_test.go

0 directories, 5 files
```

**Comment by andrerfcsantos** [comment]
I also noticed this. To give more context about the issue:

From [go 1.16 and beyond](https://go.dev/blog/go116-module-changes), all the `go` commands run now in a module-aware mode. This means that they expect a `go.mod` file to indicate the folder is a module. So:

* People with versions of go <16 won't have this problem and everything will work for them. I tested by installing several versions of go and I can confirm this is the case.
* People with go > 16 have 2 options:
  1. Add a go module in the folder with something like `go mod init <exercise_name>`
  2. Set the environment variable `GO111MODULE` to `auto`. This makes go commands work in a module-aware mode if they detect a `go.mod` in the directory, otherwise they revert to the behavior of go <16.

But like @siebenschlaefer suggested, I think the easiest solution would be to provide the `go.mod` file to the student.

**Comment by goatthinking** [comment]
go 1.16 here. Can confirm.

Suggest adding `go.mod` files in as stated by the above two individuals.

**Comment by jmrunkle** [comment]
I think we fixed this... the latest CI tests now check that every exercise directory has a go.mod file.

I ma not sure how long it takes changes in the repo to reach the website, but is anyone still seeing this now?

**Comment by bobtfish** [comment]
I'm not seeing this, I think we can close this one off @jmrunkle

**Comment by siebenschlaefer** [comment]
At least for annalyns-infiltration I can confirm that the client now downloads a `go.mod` file.
The issue seems to be fixed. (But I haven't looked at all the other exercises.)
