### ISSUE TITLE
Gross Store wrong arguments number or wrong signature of AddItem and RemoveItem functions

### ISSUE THREAD

**Issue by mickeyvip** [exercism/go#1527]
In "Gross Store" exercise the function `AddItem` has the following signature:

```go
func AddItem(bill map[string]int, item string, unit string) bool {}
```

3 arguments.

In test file it is called:

```go
ok := AddItem(bill, units, item.name, item.unit)
```

4 arguments.

The same is for `RemoveItem` function.

What should be changed? The test or the source?

**Comment by jnkroeker** [comment]
this should be addressed asap. It's very confusing to hit this wall so early in the Go track.

**Comment by geoffreywiseman** [comment]
Pretty sure it's the test -- I'm going to finish implementing and then look at a PR.

**Comment by geoffreywiseman** [comment]
There's two PRs already:
https://github.com/exercism/go/pulls?q=is%3Apr+is%3Aopen+gross

I prefer the one by `jitcompile`; both fix the problem of the mismatch, but #1523 feels right.

**Comment by jnkroeker** [comment]
yeah, i agree. 1523 is straightforward.

**Comment by geoffreywiseman** [comment]
It's worth pointing out that #1523 will break the solutions of people who modified their solutions to match the tests, which is awkward, but maybe less awkward than having a parameter that doesn't really belong there. 🤷

**Comment by jmrunkle** [comment]
Actually, I think https://github.com/exercism/go/pull/1538 is more correct based on the exemplar and the tests both agreeing that the units parameter should be there.

**Comment by jmrunkle** [comment]
Duplicating my comment from the issue I made...

The tests require the units parameter:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store_test.go#L74
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store_test.go#L155

The exemplar has the correct parameters:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/.meta/exemplar.go#L21
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/.meta/exemplar.go#L32

But the stub given to students does not:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store.go#L14
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store.go#L19

This is particularly confusing and frustrating for students using the browser editor because they cannot see the tests to know why they are failing to compile correctly.

I like my PR since it preserves one declaration per parameter: #1538
