### ISSUE TITLE
party-robot: missing prerequisites

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1585]
The `party-robot` exercise uses `string`, the `int` and `float64` types, but its [prerequisites](https://github.com/exercism/go/blob/main/config.json#L67) don't ensure that the student has learnt these concepts.

The `numbers` and `strings` concepts should be added as the prerequisite of the `party-robot` exercise.

**Comment by bobtfish** [comment]
We can't do this yet:

> `strings` depends on `numbers`, which depends on `constants`, which depends on `strings` forming a cycle:

Should be possible after #1625 is done.

**Comment by bobtfish** [comment]
This depends on issue #1613 to re-add the strings concept.

With that done the `savings-account` exercise needs to change to depend on `strings` rather than `string-formatting` - which is more correct, and also breaks a dependency cycle we get otherwise. We can then make this change to add these dependencies to the `party-robot` exercise.
