### ISSUE TITLE
elons-toys: non-struct type not explained

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1602]
The [introduction.md document]() of the `elons-toys` exercise has the following section:

> The receiver can be either a struct type or a non-struct type as in the example below.

The struct type is explained in one of its prerequisites, but the non-struct type is not define anywhere as far as I can tell. We should:

1. Remove the mention of the non-struct type from the introduction (the student does not need to know this).
2. Consider adding a prerequisite for the non-struct type (essentially finding a place to explain this concept, which could be an existing exercise or a new one). The `chessboard` exercise seems to be a nice place for this.

**Comment by bobtfish** [comment]
This should be able to be closed out now

**Comment by junedev** [comment]
Re-opening this because the PR that was merged did not cover what was explained in option 2 in the issue description. Erik meant that another exercise (e.g. chessboard) should introduce an additional concept (I would call it `type-definitions` as non-struct types is not really a Go term). Then Elons Toys can have `type-definitions` as prerequisite. Note that this change would make issue #1603 obsolete. Also keep in mind adding this additional concept might imply changes to the chessboard exercise itself as currently the stub already includes those type definitions.

I think adding type defintions to chessboard is a good idea because lots of the following use or would like to use it. However to avoid a cyclic dependency of concepts chessboard would need to be changed to use simple functions instead of methods. Which again is a change I think is worth making since the student does not really need to know methods to understand `range` (what chessboard teaches currently).

With the current content in the main branch the student could potentially work on Elons Toys without having done chessboard before so they would never see the text about how to define a type that was added there.
