### ISSUE TITLE
chessboard: don't use type definitions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1603]
The `chessboard` exercise uses type definitions, but this concept is not explained. These type definitions should be removed and the defined types themselves should be used.

**Comment by ErikSchierboom** [comment]
@junedev What is the proper Go name for a type that is defined like `type Rank []bool`? Like a type alias or something.

**Comment by junedev** [comment]
It is just called "type definition", you could also call it a custom type. A type alias is something else in Go.

I would recommend just not using this here. You could just write `[]bool` instead and since this exercise is about ranging over slices that would make it even clearer.

I would recommend introducing custom types and type aliases together with that constants exercise where they are actually needed. Not sure any other exercise urgently needs this before this point but I don't think so.

**Comment by ErikSchierboom** [comment]
Thanks. I've updated.
