### ISSUE TITLE
cars-assemble: remove `type-conversion` concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1675]
The `type-conversion` concept should be removed from the `cars-assemble` exercise. This involves:

- Removing it from the exercise's `concepts` in the `config.json`
- Replace the type conversion content from the exercise's `introduction.md` with a simple sentence how to convert from a float to an int and vice versa.

**Comment by jmrunkle** [comment]
Already removed the concept from config.json, just need to update the introduction.

NOTE: I am not certain we could technically add `type-conversion` as a prereq because it may introduce a cycle since `cars-assemble` teaches a number of basic concepts and `sorting-room` requires `interfaces` which is a more advanced concept. We can always revisit that issue later.
