### ISSUE TITLE
Blackjack exercise: can't pass two aces test

### ISSUE THREAD

**Issue by scmbradley** [exercism/go#1709]
The `LargeHand` function inputs are `isBlackjack` and `dealerScore`, so one can't test for whether the player's hand is two aces. This means there's no way to pass the `TestFirstTurn` test `pair of aces`. 

The `LargeHand` function should take the player's two cards as inputs, rather than just the boolean.

**Comment by jmrunkle** [comment]
It is not impossible to pass. Our exemplar implementation certainly passes like this:

```go
func LargeHand(isBlackjack bool, dealerScore int) string {
	// Nested if statement (no else)
	if isBlackjack {
		if dealerScore < 10 {
			return "W"
		}
		return "S"
	}
	return "P"
}
```

Two aces would have `false` for `isBlackjack` and therefore would return "P" which is exactly what the tests say we should return: https://github.com/exercism/go/blob/main/exercises/concept/blackjack/blackjack_test.go#L189

Why does this work? Because LargeHand is only called for a hand that is a blackjack or a pair of aces (when the player's hand is greater than 20).

**Comment by scmbradley** [comment]
Thanks for explaining this! I actually did this exercise successfully in another language less than a month ago. I don't know why I suddenly had such a blind spot!
