### ISSUE TITLE
weather-forecast: Test don't test for recommended commenting style in instructions

### ISSUE THREAD

**Issue by ynfle** [exercism/go#1730]
The following comment style recommendations aren't tested for:
- The [introduction](https://github.com/exercism/go/blob/main/exercises/concept/weather-forecast/.docs/introduction.md) mentions that comments should end in a period
- package-level variable should start with their name
- package doc comments should have the package name as the second word (after `Package` which is already tested for)

I'm happy to submit a PR for this, but not sure if it's supposed to be tested

**Comment by junedev** [comment]
@SaschaMann also made the following point about this (#1759):

---
I suspect this falls under "asssume the student won't cheat", but this passes the tests but clearly not the spirit of the exercise. When following TDD-principles (which many Exercism tracks tend to do), this would be a sufficient solution:

```go
// Package
package weather

// CurrentCondition
var CurrentCondition string

// CurrentLocation
var CurrentLocation string

// Forecast
func Forecast(city, condition string) string {
	CurrentLocation, CurrentCondition = city, condition
	return CurrentLocation + " - current weather condition: " + CurrentCondition
}
```

Since Go comments follow a certain format, checking their content or at least that their content is non-zero might prevent this. 

I'm not sure this is worth fixing but figured I'd bring it up anyway.
