### ISSUE TITLE
accumulate: should be removed

### ISSUE THREAD

**Issue by bmatsuo** [exercism/go#18]
The function described is a bad pattern in Go. The mailing list will tell you repeatedly that writing 'map' and 'reduce' type functions in Go results in more obscure code with worse performance.

**Comment by petertseng** [comment]
A corroborating source: https://www.reddit.com/r/golang/comments/1m25a1/map_reduce_and_filter_in_go/

The alternatives are either copy-and-paste, or reflection (with performance penalty).

---

Note amusingly that the Go track added strain in https://github.com/exercism/xgo/pull/64.

Well, I'm certainly not here to argue that strain should be deprecated, or accumulate un-deprecated. Besides, they're **both** [going to be deprecated soon](https://github.com/exercism/x-common/issues/588) anyway, so taking much further action here would not be the best use of time.

**Comment by petertseng** [comment]
More corroborating sources for those interested in reading:

https://groups.google.com/forum/#!topic/golang-nuts/RKymTuSCHS0

https://github.com/robpike/filter

**Comment by robphoenix** [comment]
Just to clarify my understanding; in xgo accumulate is deprecated (should we then delete the accumulate dir from exercises?) and strain will be deprecated in the future, both to be replaced by List Ops. However functional programming concepts for operating on lists, such as map, filter & reduce are actively discouraged in Go, so will we actively avoid implementing the List Ops exercise? (I have a soft spot for FP and was thinking of implementing it) If so, do we want to mention this somewhere more prominently than an Issue, and do we want to remove it from the list of unimplemented exercises on the exercism.io Go language page?

**Comment by petertseng** [comment]
> should we then delete the accumulate dir from exercises?

The disadvantage of that would be that I would no longer be able to fetch the exercise via `exercism fetch go accumulate` (whereas I now can). The advantage would of course be that we no longer have to maintain the files of the deprecated exercise. If the advantage outweighs, then delete.

> However functional programming concepts for operating on lists, such as map, filter & reduce are actively discouraged in Go

What I see from the three sources is that attempting to do it **generically** incurs a performance penalty, because it necessitates using reflection. If we do it for *specific types*, maybe it's fine. Strain does it for specific types. So does accumulate, in fact.

> so will we actively avoid implementing the List Ops exercise

If nobody comes forth with a good reason to not implement it, I don't see why we wouldn't.

> do we want to mention this somewhere more prominently than an Issue

Might be a good idea - I don't think **any** track has a solution to this problem... because JSON doesn't allow for comments. We can do it a custom way by adding a custom key to the JSON file, `"deprecation_reasons": { "binary": "deprecated in favour of all-your-base" }` or similar.

> do we want to remove it from the list of unimplemented exercises on the exercism.io Go language page?

Ah, right. If we do that, I hope that adding it to `forgone` would be enough.

---

> Well, I'm certainly not here to argue that strain should be deprecated, or accumulate un-deprecated. 

Okay, I've decided that I lied when making this statement. I hereby suggest this track un-deprecate `accumulate`, until `list-ops` is added to this track. If `list-ops` will be added within the next few days, then there's no point in adding the churn, but if it will be a while in coming, why not show `accumulate`?

One can argue that if you denounce something before you've tried it, you lose perspective on the reason why you're denouncing it. So if we exclude `accumulate` from this track, we don't let students try writing map, and so they don't gain perspective. See how https://github.com/robpike/filter says the author wished to determine how hard it was to implement map/filter/reduce in Go.

If we want to give them the exposure and then warn them that it's not something they should try to do, we're free to add something to HINTS.md or something.

**Comment by robphoenix** [comment]
> if ... we don't let students try writing map, and so they don't gain perspective

I agree, better to do and fail then be told.

> If nobody comes forth with a good reason to not implement it, I don't see why we wouldn't.

:+1: 

> If we do it for specific types, maybe it's fine. Strain does it for specific types. So does accumulate, in fact.

custom-set is also a good example of this

> Ah, right. If we do that, I hope that adding it to forgone would be enough.

What is the forgone section in the config.json for? I did some digging but couldn't find an answer.

>  I hereby suggest this track un-deprecate accumulate, until list-ops is added to this track. 

I'm going to move this into it's own issue.
