### ISSUE TITLE
"See what's changed" resulting in errors

### ISSUE THREAD

**Issue by dstockto** [exercism/go#1818]
I got a number of outdated exercise warnings on various Go exercises. Some of them updated without issue, but quite a few are opening a nearly full screen loading spinner followed by a modal which says "Sorry - it seems that we can't work out what needs updating for this exercise. We've been alerted and will have a look.". This modal flashes and the console indicates the error boundary is being hit repeatedly along with a bunch of calls to bugsnag.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/775393/136318113-4cdf08ea-6ac4-4595-8bce-3dfd69121a59.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/775393/136318179-0cef922a-efd1-4122-be0a-9bc2f0f1f320.png">

Of course now that I come here to write it up, I am only getting the spinner on some exercises.

The following exercises are the ones I'm currently having issues with:

* Scrabble Score
* Isogram
* Gigasecond
* Darts
* Acronym
* Phone Number
* Scale Generator
* Bob
* Collatz Conjecture
* Matching Brackets
* Sieve
* Grains
* Clock
* Luhn
* Space Age
* Leap
* Nucleotide Count
* Rna Transcription
* Proverb
* Roman Numerals
* Pangram
* Reverse String
* Word Count
* Run Length Encoding
* Largest Series Product
* Isbn Verifier
* Nth Prime
* Atbash Cipher
* Phone Number
* 

Here's one of the console errors:

```
HandledError: Sorry - it seems that we can't work out what needs updating for this exercise. We've been alerted and will have a look.
    r internal-2cd1cc400f7e0b82ee0a.chunk.js:2
    r internal-2cd1cc400f7e0b82ee0a.chunk.js:2
    a ErrorBoundary.tsx:109
    g ErrorBoundary.tsx:101
    promise callback*g/< ErrorBoundary.tsx:90
    React 2
    unstable_runWithPriority scheduler.production.min.js:311
    React 3
    F scheduler.production.min.js:205
    onmessage scheduler.production.min.js:96
bugsnag.js:2539:17
    n bugsnag.js:2539
    n bugsnag.js:2539
    React 9
    unstable_runWithPriority scheduler.production.min.js:311
    React 5
    g ErrorBoundary.tsx:101
    (Async: promise callback)
    g ErrorBoundary.tsx:90
    React 2
    unstable_runWithPriority scheduler.production.min.js:311
    React 3
    F scheduler.production.min.js:205
    onmessage scheduler.production.min.js:96
```

I did save one of the bugsnag requests as HAR if needed. It is gigantic and looks like it may contain personal information so I have not posted here. I can provide upon request if needed though.

**Comment by junedev** [comment]
@andrerfcsantos Are those the exercises where you added the cases file to editor.test maybe?

cc @ErikSchierboom

**Comment by andrerfcsantos** [comment]
@junedev I believe so.

I opened an issue a few days ago on exercism/exercism: https://github.com/exercism/exercism/issues/6010

One interesting case is the Allergies exercise. It had an update after that change, and because of that extra change, I was able to update it. But the changes to files.test seem to have the effect we intended.

While we don't get confirmation that this is maybe a bug site-wide, should we revert that change or add the extra test cases file to files.editor instead of files.test?

**Comment by ErikSchierboom** [comment]
This is indeed a known issue, where `files.editor` files are not included in the diff. I'll look into it.

**Comment by ErikSchierboom** [comment]
> Just to clarify, we added something to files.test, not files.editor, might of course be the same issue nevertheless.

That sounds like a different error. I'll check

**Comment by ErikSchierboom** [comment]
I've looked into this, and here is what's happening:

- Commit https://github.com/exercism/go/commit/4065546b0dde09d893967c067a70a67a0a11c44b updated the `.meta/config.json` of the aforementioned exercises
- The exercise's Git SHA was updated to that commit's SHA (4065546b0dde09d893967c067a70a67a0a11c44b)
- The solution Git SHA remained the same, which is why you see the "The exercise has been updated" message
- The diff checks to see if any of the exercises files (instructions, and test files) are in the diff, but they're not so the diff is empty

I think what we need to do is detect this situation and consider addition/removal of files in the `.files` key of the `.meta/config.json` as a sort of "manual" diff, if they're not modified in the same commit as the update to the `.meta/config.json` file

**Comment by junedev** [comment]
@ErikSchierboom Do you think this can be fixed soon-ish or should we perform some tiny change in all those exercises so at least  the diff process does not run into this error state anymore? That seemed to be a workaround, as noted in https://github.com/exercism/go/issues/1818#issuecomment-937529095.

**Comment by dstockto** [comment]
I'm not completely sure this is relevant but it sounds like it may be - if you're using the entire repository hash in order to determine the contents of subdirectories it might be better to try something that narrows it to just the subset you're looking at. I do the same for another project where a single project contains multiple UI apps and I use the hashes of combinations of directories and files to determine if I need to make a build or not. I'm using something like this:

```
git ls-files -s $directoriesString | git hash-object --stdin
```

`$directoriesString` is just a space separated list of directories and files that are the inputs to the build. If this is irrelevant, my apologies. I am not familiar with how this currently works.

**Comment by junedev** [comment]
This is the issue for showing multiple test files: https://github.com/exercism/exercism/issues/6033

This is the issue for the problem with the diff when new files are added: https://github.com/exercism/exercism/issues/6010

I am closing this one as we have those separate issues now and none of the issues are Go specific.
