### ISSUE TITLE
Golang chessboard output

### ISSUE THREAD

**Issue by Lewiscowles1986** [exercism/go#1826]
Following on from #1822 I was thinking that perhaps we could further enhance and help learners by outputting the chess-board for each test run.

@jmrunkle suggested creating an issue (which I should have really done before launching into a PR on hints :wink:)

I Noticed this when viewing the tests (not online editor)
https://github.com/Lewiscowles1986/go/blob/1f67dcc7ccf5b4acf3c8d80107ff6993d821f0ac/exercises/concept/chessboard/chessboard_test.go#L7-L18

I thought. Oh if only each test had that, the description would not be a barrier... To be clear I wrote out by hand to visualise the tasks, and then iterated from there. The text still isn't especially clear to me, but I tried in hint to help me once I had solution.

Perhaps once someone has solution, text makes more sense, so I am thinking maybe this would help others. What do you think?

**Comment by Lewiscowles1986** [comment]
I Also noticed that despite being told #1822 was correct, I still do not get hints https://exercism.org/tracks/go/exercises/chessboard/edit
This is unfortunate as it means I contributed a dud. Any assistance on verification prior to merging would be appreciated.

**Comment by Lewiscowles1986** [comment]
Questions:

- Do you think it would benefit users to have this as part of hints, or inline for first iteration?
- Is there a way to test this locally?

**Comment by junedev** [comment]
@Lewiscowles1986

**Regarding the exercise in general**
I thought a bit more about how to avoid the confusion which is rank and which file altogether. I realized that originally, one was labeled with numbers and the other one with letters. You can see this here: https://github.com/bobtfish/exercism-go/blob/a07d694538506b92150035c9ea8a1d45d3b4152f/exercises/concept/chessboard/chessboard_test.go
Then, because they used byte for the letters (which the student going through the concept tree does not know yet) that was changed to int and this is when people started to be confused (#1732).
The better fix to address the problem with byte would have been to just switch to string instead which the student already knows at this point. I think we should really go back to letters and numbers to make it very easy to distinguish rank and file. Are you interested in fixing this as part of your PR?

**Regarding showing the "image" in various places**
Independent of whether it works or not to show this as part of the test output, I don't think it is a good idea because Exercism is about gaining fluency and that imo includes being able to have a mental modal for nested data structures. Those nice images would not represent a real live experience working with those data structures.
Regarding separate images to show rank and file that you proposed, I think if we go back to the letters and numbers as described above, then one chessboard image in the instructions should be enough to clarify things.

**Comment by Lewiscowles1986** [comment]
I've updated the PR accordingly.

Lets park the mental model chat, as I neither agree nor have the time to fully explore it.

Thank you for your time reviewing, leaving breadcrumbs etc. Enjoy the week.
