### ISSUE TITLE
parallel-letter-frequency: have bigger test cases to show the benefits of concurrency

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#1941]
On `parallel-letter-frequency`, one thing that often students find weird and talk about is how the sequential solution is often more performant than the concurrent one.

This happens because we have small test cases. Not only we have few strings for which to concurrently compute the letter frequencies, but the strings themselves are small. This makes the overhead of creating goroutines/channels/waitgroups not worth performance-wise.

With this issue I intend to open the discussion if we should do this. I understand it's not essential for the exercise but I think it would be a nice touch for students paying attention to the benchmarks to see that their efforts to make the solution concurrent paid off, not only as a learning experience, but also in terms of performance.

**Comment by junedev** [comment]
I am smiling about this a little because this is also what happens in real world scenarios a lot. People use channels and it gets slower. :wink: 

Now to comment on the issue: I totally agree that it would be great that using channels actually makes sense when looking at the benchmark. The question for me is, how big (file size) do we need to make the test data so that the current solution is significantly faster then the sequential one? Let's say we would need to add 1MB of test data to make this visible then I wouldn't do it because I don't want to stress the website (and with lesser severity also CLI users) with downloading that much stuff. If its in the range of idk <10KB or something, then I think we should do it. Do you already have a feeling for how much longer the texts would need to be?

**Comment by andrerfcsantos** [comment]
Did a quick test today and the good news is that our tests don't need to be that big for this difference to show up. These are the current tests on my machine:

```console
$ go test -bench .
goos: windows
goarch: amd64
pkg: letter
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkSequentialFrequency-8             54391             21340 ns/op
BenchmarkConcurrentFrequency-8             35836             32870 ns/op
PASS
ok      letter  3.025s
```
Current `parallel_letter_frequency_test.go` size: 2277 bytes

I made the existing strings a little bit bigger and added a 4th one:

```console
$ go test -bench .
goos: windows
goarch: amd64
pkg: letter
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkSequentialFrequency-8             20692             59284 ns/op
BenchmarkConcurrentFrequency-8             24352             49196 ns/op
PASS
ok      letter  3.771s
```

New `parallel_letter_frequency_test.go` size: 4189 bytes

So I think making this change is viable.

**Comment by junedev** [comment]
I think after our discussion on Slack this is ready to be worked on now.

Here are the tasks:
- [ ] In the test file, use texts that are roughly twice as long as the current ones and add a fourth entry of such length to the slice that is used for the test. (It would be nice to stick with the theme of having actual texts from different languages instead of "Lorem Ipsum" texts.)
- [ ] Use the solution below as new example solution. The current one does not really leverage the concurrent processing much and performs worse that the sequential solution in a lot of cases.

```go
package letter
​
import "sync"
​
// FreqMap records the frequency of each rune in a given text.
type FreqMap map[rune]int
​
// Frequency counts the frequency of each rune in a given text and returns this
// data as a FreqMap.
func Frequency(s string) FreqMap {
	m := FreqMap{}
	for _, r := range s {
		m[r]++
	}
	return m
}
​
func ConcurrentFrequency(texts []string) FreqMap {
	res := make(FreqMap)
	ch := make(chan FreqMap, 10)
​
	var wg sync.WaitGroup
​
	wg.Add(len(texts))
​
	for _, text := range texts {
		go func(t string) {
			ch <- Frequency(t)
			wg.Done()
		}(text)
	}
​
	go func() {
		wg.Wait()
		close(ch)
	}()
​
	for freqmap := range ch {
		for letter, freq := range freqmap {
			res[letter] += freq
		}
	}
​
	return res
}
```

**Comment by junedev** [comment]
In #2067 @lburnett88 pointed out that a lot of community solutions are not really concurrent and the tests past whether there is a concurrent solution or not. We probably can't fail near-sequential solutions in the test runner but we could add instructions in the instructions.append.md file how students working locally can check themselves whether they did it properly using the benchmarks.
