### ISSUE TITLE
Unclear why exercise is locked

### ISSUE THREAD

**Issue by tehsphinx** [exercism/go#2041]
In this case it is not clear why an exercise is locked.

![image](https://user-images.githubusercontent.com/6624571/147669831-509ff6f8-ad12-49c6-b2cd-81f2253e02d1.png)

I checked the dependency json and there are a lot more deps not connected in the graph. Is there something that can be done about that?

**Comment by andrerfcsantos** [comment]
That is a good point.

In that particular situation, do you know which of the dependencies is blocking the Maps concept?

**Comment by jmrunkle** [comment]
That looks like an issue with the graph rendering rather than something specific to the go repo.

The maps concept has 5 prerequisites: https://github.com/exercism/go/blob/4ed2ad1680b80ea55d0cf13aaa4fb2f675d40932/config.json#L165-L169

Only the last one (functions) is being shown in the UI. It is missing all of the others like "conditionals-if" and "numbers". I think this issue belongs in a component where the UI rendering for the graph is written, but I do not know which component that is. Maybe we can start by moving it to exercism/exercism?

**Comment by junedev** [comment]
This is intentional to avoid too many lines in the concept tree, see https://exercism-team.slack.com/archives/GC3K95MRR/p1639488266184100?thread_ts=1639483090.183400&cid=GC3K95MRR on Slack.

In the hover box it should say what is needed to unlock.
I will close this issue.
In case someone has a big problem with the current state, feel free to open an issue in exercism/exercism.

**Comment by tehsphinx** [comment]
@junedev: I kind of expected this to be intentional, to not overload the graph with too many lines. The problem is, that the hover box does not show any information on prerequisites either.

![image](https://user-images.githubusercontent.com/6624571/147742074-7b0224af-cfe6-419e-8af6-230afdaecdf5.png)

As a student who doesn't know where to look in the config files, I currently can't find a way to get to this information. If it should be in the hover box, can you point me to the file where it should be added?

**Comment by junedev** [comment]
@tehsphinx Can you clarify what you mean by "the hover box does not show any information on prerequisites". The hover box screenshot you posted says that you need to unlock "Conditionals Switch". Is that not correct?

**Comment by tehsphinx** [comment]
Oh, right. Didn't see that as I was expecting like a list of items needed to unlock this. My bad 😁
