### ISSUE TITLE
Make generators run under new directory structure

### ISSUE THREAD

**Issue by ilmanzo** [exercism/go#2043]
run-generators script is not aware of the new directory structure; seems it expects to find all exercises under exercises/* , while they have been splitted in concept, practice, shared folders. 
When ran manually, each generator gives error about missing import
```
Generating acronym
gen.go:7:2: cannot find package "." in:
	/home/andrea/projects/exercism-go/exercises/gen

```

**Comment by andrerfcsantos** [comment]
Thanks for opening an issue about this.

At a quick glance, the problematic line seem to be this one:

https://github.com/exercism/go/blob/4ed2ad1680b80ea55d0cf13aaa4fb2f675d40932/gen/gen.go#L108

Since generators only make sense for practice exercises, seems to me a quick fix for now would be to add `"practice"` to that path, but other things might have changed too.

**Comment by andrerfcsantos** [comment]
I took a look at this issue and my previous comment is wrong. The line I mention above refers to a path in problem-specifications that did not change. I got the generator working for an exercise, here's the changes that need to me made here:

- [ ] The import path to the generator in `exercises/practice/<exercise>/.meta/gen.go` needs to be updated. Currently it refers to `"../../../gen"`, but since we have one more directory level, now, it must be changed to `"../../../../gen"`. A global find/replace should do the trick.
- [ ] The README.md of the repository needs to be updated with a new command to run the generator. For the relative import mentioned above to work, we need to deactivate Go modules when running the command. This can be done by setting `GO111MODULE=off`. In addition, the current command still refers to the old folder structure, as it still reads `go run exercises/<exercise>/.meta/gen.go`. This must be changed to `go run exercises/practice/<exercise>/.meta/gen.go`. So, the whole command should look like: `GO111MODULE=off go run exercises/practice/<exercise>/.meta/gen.go`
