### ISSUE TITLE
logs-logs-logs: Some details potentially missing in hints.md and introduction.md

### ISSUE THREAD

**Issue by ssilva** [exercism/go#2070]
I am not sure whether these are by design (i.e. we want the user to search the Go docs) or just an oversight, but after going through the exercise, I feel that:

1. in [hint #2 (`hints.md`)](https://github.com/exercism/go/blob/b00b970fdcc9be8120a312258b446b903fdb0d66/exercises/concept/logs-logs-logs/.docs/hints.md?plain=1#L9), it should be mentioned that a `rune` must be first converted before it is concatenated with a `string`
2. in [the very last exemple of `introduction.md`](https://github.com/exercism/go/blob/b00b970fdcc9be8120a312258b446b903fdb0d66/exercises/concept/logs-logs-logs/.docs/introduction.md?plain=1#L90), there should be an `import "unicode/utf8"` (because `utf8.RuneCountInString()` is used)

**Comment by andrerfcsantos** [comment]
Thanks for bringing this to our attention!

1. Indeed, the hints should mention how to convert a rune to a string, since the solution will very likely use it. Looking at the whole file, the hints for task 3 could probably also get more love and be me more complete.
2. I agree. I can see how someone new to Go can be confused by seeing the `utf8` being used and seemingly coming from nowhere.
