### ISSUE TITLE
Need for speed: clarify instructions

### ISSUE THREAD

**Issue by LeamHall** [exercism/go#2105]
Adding more tests and more skills for the users is great, but if you add a test, make sure that it follows the instructions in the exercise. Or, get the instructions modified to make your test case valid. 

For example, in "need for speed" there's a conflict between the instructions and the tests. The instructions say: "Assume the car is just starting the race:", which implies a fully charged battery. However, some of the tests assume the car starts with less than a full battery.

If the tests do not reflect the preconditions then users will lose confidence in the training.

**Comment by andrerfcsantos** [comment]
Thanks for opening this issue!

The new tests without a fully charged battery were added recently, but I don't think they invalidate the instructions necessarily. 
Maybe the problem here is that `"Assume the car is just starting the race"`  is ambiguous and opens up a lot of interpretations.

It can be read as implying a fully charged battery, but it can also be interpreted as implying that the car starts with `distance==0`. Neither are correct assumptions as I see it. I believe that sentence is trying to imply that students should ignore the `distance` field in the car for the purposes of this computation, by saying "the car might have distance > 0, but ignore it, assume the car is just starting the race and that distance value was driven before the race". So, in the end I think the ultimate goal of that sentence is to make students just ignore the `distance` field on the car and just consider the track distance, current level of battery and battery drain of the car.

So I think we should change the instructions to make this a bit more explicit if possible, by not having a sentence that can be ambiguous on what is trying to say.

**Comment by LeamHall** [comment]
I agree completely! I didn't see a way to edit the text of the exercise, and I'm coming back to Go again so my skills aren't that great. Specifying that the distance can be > 0 and the battery can be < 100 would help the learner know that they are being intentionally challenged.

Thank you for understanding the issue.

**Comment by nahuakang** [comment]
I'll claim this :)
