### ISSUE TITLE
Sorting Room - suggestions re task description and additional test case

### ISSUE THREAD

**Issue by norbs57** [exercism/go#2106]
In the sorting-room exercise task description, "Section 2. Describe a number box",  it says:
 > Jen wants numbers to...

I wonder if this should be:  
 > Jen wants number boxes to...

In the same section, the sample code  refers to 
> numberBoxContaining{12.345}

This looks odd as number boxes supply int- values, not floats. This could be fixed by using 12 instead of 12.345, for example. 

In sorting_room_test.go, function TestExtractFancyNumber currently has only one non-FancyNumber  test with a string "two" that fails conversion to int. Because of this, the test can be passed without the code actually checking the type of the fnb argument. Adding a test case similar to below should fix this: 
```
{ description: "Extract 4 packed as a different fancy number returns 0",
  input:       differentFancyNumber{"4"},
  want:        0,
 } 
```

**Comment by andrerfcsantos** [comment]
Nice catches!

We have a similar test for task 4, unfortunately we don't have one for task 3, so this is a good addition indeed. To summarize, the changes that must me made:

[ ] Change the description of task 2 to refer to a number box as suggested.
[ ] Change the example of task 2 to have an int instead of a float
[ ] Add a test with something that is not a `FancyNumber` but has a string that is a valid number, which should want 0 as the result

**Comment by norbs57** [comment]
Hi Andrew,

Thanks for reviewing that issue.

I don't have much experience with Github but I would be happy to have a go
at fixing it.

I am new to Exercism and I am unsure of the etiquette. In general, if I
have suggestions regarding a Go track exercise, should I raise it as an
issue or would it be better to try and contact the exercise authors or the
Golang track maintainers (first)?

Best,
Norbert

**Comment by andrerfcsantos** [comment]
Go for it! I'll assign this to you.
