### ISSUE TITLE
Binary Search Tree: map functions - mismatch with specs 

### ISSUE THREAD

**Issue by norbs57** [exercism/go#2113]
File binary_search_tree.go defines two (higher-order) functions MapString and MapInt.  There seems to be a mismatch between the type of these functions and their specs in that source file:

- The type (and name) of the Map functions suggests that the argument f will be applied to each of the elements of the tree that is to be transformed into a slice.
- The specs do not mention the function argument f at all. Instead, these specs are more in line with Map-functions that do not take a function argument.   

There are at least four different ways in which we could address this issue: 

(A) Keep the function types the same, update the specs and add some test cases for different f-arguments. 

(B) Keep the specs, change both Map-functions to no-argument functions, and update the tests accordingly. 

(C) Keep function MapInt as it is and replace MapString with a no-argument String function. The latter could be implemented with or without invocation of MapInt. This would entail adding test cases for MapInt and updating MapString tests to String tests. 

(D) Remove the Map-functions from this exercise - arguably they do not go all that well with the topic of binary **search** trees. Instead, we could reuse some of the material for a new, separate exercise on map-functions for different types of trees, graphs, slices, etc.  In this context, it is worthwhile remembering that Go is about to acquire generics. Once this has happened, functions like MapString and MapInt can be defined as special instances of more generic Map functions. 

If we keep the Map-functions, then it would be good to mention them in the instructions and maybe also have something about them in README.md.

**Comment by andrerfcsantos** [comment]
Looking at the the [problem specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/binary-search-tree), the canonical tests seem to require 2 things from this exercise: adding new elements to the tree and getting the elements of the tree ordered.

In Go it seems the second requirement gave origin to the map functions. The point of them is to force the student to write traversal code for the entire tree, Go added the additional requirement of optionally transform the elements before they are included in the final collection.

I agree we should just have one function to traverse the tree and that function should take no arguments. At that point, instead of `Map***`, we can call the function `SortedData` or something similar. I also took a quick look at how other tracks do this and they also seem to have functions without any argument for this requirement, so I think we should do it too, as it makes the exercise clearer.

So, the tasks here are:

* Remove the `Map` functions and just have one function to get the data sorted.
* Update the tests accordingly
