### ISSUE TITLE
Lasagna Master: Improve functions introduction

### ISSUE THREAD

**Issue by shapito27** [exercism/go#2181]
https://exercism.org/tracks/go/exercises/lasagna-master

Introduction for exercise says:

> Functions in Go pass their arguments by value. This means that the arguments are copied, and any changes to those arguments within the function will not be seen outside the function.

Task 3 says:

> Write a function AddSecretIngredient that accepts two slices of ingredients of type []string as parameters. The first parameter is the list your friend sent you, the second is the ingredient list of your own recipe. The last element in your ingredient list is always "?". The function should replace it with the last item from your friends list. Note: AddSecretIngredient does not return anything - you should modify the list of your ingredients directly. The list with your friend's ingredients should not be modified.

Resulting code for task 3:
```
func AddSecretIngredient(friendsList []string, myList []string) {
	myList[len(myList)-1] = friendsList[len(friendsList)-1]
}
```

I don't understand, how newbie will understand why they pass the slice by value to the function but myList will be changed outside. 

I suppose it will be better to clarify why it happens.

**Comment by junedev** [comment]
Good catch! The introduction of the functions concept needs to be fixed here. 

There is a general challenge here though. While we need to teach about functions early in the concept tree/learning path because following concepts rely on those prerequisite learnings, the real deep dive into points comes later in the tree because it needs a separate exercise as there is a lot to cover. So will always be some handwaving involved here that will be cleared up later. We could make this learning exercise only about functions that deal with values that are not pointers but then we would need some other place/concept to come back to functions with pointer arguments. That also does not seem like a good option.

I would suggest the following improvements to address the issue at hand.
* After the example with the primitive values, explicitly state that the value can be a pointer (reference to something) and in that case the pointer, not the underlying data is "copied".
* Reduce the pointer example code. It does not add value for the exercise or concept. This will be covered in all its details in the pointers concept/exercise. For the actual scope of the functions concept/exercise it would be sufficient to say that pointer types can be recognized by the `*` in front of the type in the function signature.
* Explicitly state that slices and maps are exceptions to the above as they are also pointer types even though there is no explicit `*` in the type.

Changes made to the introduction of the exercise should also be applied to the introduction and about of the functions concept.

**Comment by nahuakang** [comment]
I can work on this. Happy to be assigned to this issue.

**Comment by junedev** [comment]
@nahuakang Thanks for helping out with this!
