### ISSUE TITLE
Improve exercise nth-prime

### ISSUE THREAD

**Issue by MikaeelMF** [exercism/go#2224]
Hi all!

While I was solving nth-prime exercise I figured out there might be two problems regarding this exercise:
1) The description is really vague regarding what the main function should return. It is not clear why there is a boolean field,
2) Looking at test cases, one can figure out that the solution should return if the input is less than 1 or not (since there is no 0th prime number!) and it does not contribute to the main point of exercise at all!

The first problem arises because of the second one and I believe two solutions can help the exercise become better here:
1) Either set the input limit from n>=1 so there would be no need to return a boolean (which makes the exercise much cleaner and does not hurt the main goal of itx)
2) Require to panic or return an error in case of an input less than 1 and make it clear in the description that the input must be bigger than 1 and in other cases it should return an error

I was wondering what is your thoughts on this.
P.S. I did not mention this problem in [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/nth-prime) because although the description is vague there as well but looking at [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/nth-prime/canonical-data.json) you can see there need to be an error in case of n=0

**Comment by andrerfcsantos** [comment]
Thanks for opening an issue about this,

> Require to panic or return an error in case of an input less than 1 and make it clear in the description that the input must be bigger than 1 and in other cases it should return an error

I agree that returning an error here would be more idiomatic than returning a boolean. Since this exercise has a test generator that generates test cases from problem-specifications automatically, the test generator [gen.go](https://github.com/exercism/go/blob/main/exercises/practice/nth-prime/.meta/gen.go) for the exercise must be adjusted accordingly.

> The description is really vague regarding what the main function should return. It is not clear why there is a boolean field

If there's something that you feel like adding to the description that could benefit all the tracks, then that suggestion must be made in the problem-specifications directly. For clarifications related with the Go version of the exercise specifically, we can add them in a `.docs/instructions.append.md` file. In that file, it's fine to explain that the function returns 2 values, and the second one might be an error. In the site, the contents of this file will appear after the contents in the `.docs/instructions.md` file.

**Comment by MikaeelMF** [comment]
Great! Thank you for your clarification!
So if it is okay with you, I will correct the [gen.go](https://github.com/exercism/go/blob/main/exercises/practice/nth-prime/.meta/gen.go) and write a `instructions.append.md` to explain the expected function's return value in Go.

For general clarification of the problem, I will create an issue in problem-specification.

**Comment by andrerfcsantos** [comment]
Sure, Go for it :)

I'll assign this to you just to signal others that you are working on this.

**Comment by MikaeelMF** [comment]
Great!

**Comment by andrerfcsantos** [comment]
Merged! Feel free to open the PR in problem specifications repo and import any changes there to the Go track later.
