### ISSUE TITLE
Grains

### ISSUE THREAD

**Issue by eklatzer** [exercism/go#2250]
Hey, when mentoring `Grains` (https://exercism.org/tracks/go/exercises/grains) I was asked, why the person must iteration from `0` to `65` and why this works:
```
func Total() uint64 {
	var total uint64 = 0
	for i := 0; i <= 65; i++ {
		total += uint64(math.Pow(float64(2), float64(i)))
	}
	return total
}
```
After a bit of debugging I found out, that this is caused by an overflow:
```
2^62=4611686018427387904     new sum: 9223372036854775807
2^63=9223372036854775808     new sum: 18446744073709551615
2^64=9223372036854775808     new sum: 9223372036854775807  <-- overflow
2^65=9223372036854775808     new sum: 18446744073709551615
```
When adding `2^65` after the overflow the result is the result that was expected and all tests pass. Is there anything we could do, to detect this, as this is not the expected behaviour as this would be:
```
func Total() uint64 {
	var total uint64 = 0
	for i := 0; i <= 63; i++ {
		total += uint64(math.Pow(float64(2), float64(i)))
	}
	return total
}

```

**Comment by andrerfcsantos** [comment]
That's a good catch. I'm not sure there is really a good way to test for this or even if it's something we want to test.

A possible way to detect this overflow (at least the basic cases) would be to parse the AST of the solution and try to detect loops or shift operations that would cause an overflow, but this is probably something that the analyzer should do and not the tests for the exercise. 

However, I'm fine with leaving this sort of overflow discussion to mentoring sessions. It's something that deserves a proper explanation from a mentor, as the student still might be confused and frustrated with a failing test they possibly don't understand. Mentors can also point this out, even if the students don't ask explicitly. We can also mention this in the mentor notes. I'm drafting some things to include in mentor notes for exercises - I made a note to include this for the grains exercise.

**Comment by eklatzer** [comment]
Do you want me to summarize the problem for the mentor nodes?

**Comment by andrerfcsantos** [comment]
@eklatzer That would be great! Feel free to message me on slack so we can exchange some notes :)

**Comment by junedev** [comment]
@eklatzer The mentor notes live in this repository/folder: https://github.com/exercism/website-copy/tree/main/tracks/go/exercises
It would be great if you could create a PR there. If you feel like it, you can create "full" mentor notes for grains like we have for hamming https://github.com/exercism/website-copy/blob/main/tracks/go/exercises/hamming/mentoring.md. Otherwise, you can also just add the usual headers and write `TODO` below those and then add your content in some section called `Integer Overflow` or similar. 

When transferring the content, I don't think you need to include the part about how binary works. I think we can assume that mentors and even most students know that.

**Comment by junedev** [comment]
Yes, I forgot to link the issue before merging. Thanks for the reminder.
