### ISSUE TITLE
Exercise diamond \n at end of diamond

### ISSUE THREAD

**Issue by eklatzer** [exercism/go#2258]
Hey, as discussed in #2255 we could remove the required `\n` at the end of the diamond, as also the instructions do not have one as you can see here: 
Diamond for letter 'C':
```
··A··
·B·B·
C···C
·B·B·
··A··
```

**Comment by andrerfcsantos** [comment]
Alternatively, we can make the tests accept both forms, by comparing the newline trimmed versions of expected vs. actual. This might make the tests harder to debug though.

I don't think there's a right answer here because what's more convenient depends on the algorithm the student is using. I'll post here the two kinds of solutions I see the most when mentoring, one would benefit from having a `\n` at the end, and the other would prefer for the `\n` to not be there.

## `strings.Join` based solutions - prefers no `\n` at the end

If the student computes all the rows and puts them in a slice, then the more natural approach to generate the final string is using `strings.Join`:

```go
var rows []string

for keepGeneratingLines {
    row := ComputeRow(...)
    rows = append(rows, row)
}

return strings.Join(rows, "\n")
```

In this case not having a final `\n` is desirable, just so the student doesn't have to write `strings.Join(slice, "\n") + "\n"`.

## `strings.Builder` based solutions - prefers `\n` at the end

However, some students also build the string using `strings.Builder`:

```go
var b strings.Builder

for keepGeneratingLines {
    row := ComputeRow(...)
    b.WriteString(row)
    b.WriteString("\n")
}

return b.String()
```

In this scenario, it is more convenient for the final `\n` to be there, just so the loop doesn't have any "last row" special condition.

**Comment by junedev** [comment]
Thanks @andrerfcsantos for the insights! I forgot to consider the different approaches here.

**Comment by eklatzer** [comment]
Thanks @andrerfcsantos for the examples. There is of course no right answer for this issue, but we should at least adjust the instructions to make clear what is expected (`\n` or not). Which version do you prefer?

**Comment by junedev** [comment]
I pondered this a bit more and my tendency is now towards actually requiring no line break at the end as @eklatzer originally suggested. Contrary to what I wrote before, I think that it actually adds value to the exercise because the scenario that you build something up line by line but then need to do something different at the end also happens in the real world. 
Let's say we stated clearly in the instructions that there should not be a line break at the end. Then there are two options for students.
* They already used a way of solving the exercise that incorporates the requirement of no new line at the end (e.g. via strings.Join). In this case there is no additional difficulty which is fine.
* Their approach leads to a line break at the end (e.g. when using builder or string concatenation) then they need to deal with removing it before returning the result. In this case the exercise is a bit harder but I think in a good way because besides being quite a realistic scenario, it is one of these "the devil is in the detail" cases which was a tag line of Exercism in V1 I think. There are quite some exercises which have similar vibes.

A mentor could then potentially even mention that the issue with the new line does not arise with the strings.Join approach. Or if someone used a loop but excluded the last iteration to handle it separately you can discuss this approach vs. running the entire loop and fixing the line break afterwards.

If people disagree with my favorite solution described above, my second favorite would be the one with making the tests agnostic to the last line break. Shouldn't be too hard as we only need to do "if it is there, remove it before checking against the expected result" or the other way around. If we go with this, there should be a comment in the test file about why we do that part though.

**Comment by andrerfcsantos** [comment]
> I pondered this a bit more and my tendency is now towards actually requiring no line break at the end as @eklatzer originally suggested. Contrary to what I wrote before, I think that it actually adds value to the exercise because the scenario that you build something up line by line but then need to do something different at the end also happens in the real world. Let's say we stated clearly in the instructions that there should not be a line break at the end.

I also agree with this. I think my position of allowing both comes from my brief experience in competitive programming, where my team got screwed a lot by these kinds of things. Failing a submission because of missing or extra whitespace at the end always gave me this "unfair" feeling.

I agree with imposing no extra line at the end, but we must state that clearly in the exercise description and we must ensure the test output shows clearly that is the case. A failing test because extra or missing whitespace should scream that is the case. Using `%q` might not be enough, especially for exercises like the diamond exercise where the strings are quite big.

> Their approach leads to a line break at the end (e.g. when using builder or string concatenation) then they need to deal with removing it before returning the result.

One more argument in favor of requiring no extra line at the end is that you don't actually need to remove the extra line at the end, or add a special condition inside the loop. Instead of:

```go
var b strings.Builder

for keepGeneratingLines {
    row := ComputeRow(...)
    b.WriteString(row)
    b.WriteString("\n")
}

return b.String()
```

You can handle the first case especially instead:

```go
var b strings.Builder

row := ComputeRow(0)
b.WriteString(row)

for generateLinesExcludingFirstOne {
    row := ComputeRow(...)
    b.WriteString("\n")
    b.WriteString(row)
}

return b.String()
```

This is actually the way `strings.Join` [works internally](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/strings/strings.go;l=425).

The issue here is that such solution might not be obvious for students, and they might have all the logic to create a line in the loop itself and not in a function like `ComputeRow`. But I'm ok with this not being obvious and leave this to mentor discussions.

**Comment by eklatzer** [comment]
So summarized: no `\n` at the end but a specific test (or maybe included in the other tests) that checks if the only error is a additional `\n` at the end?

**Comment by andrerfcsantos** [comment]
Yes :) I don't think it needs to be a new test, can be included in the existing ones.

**Comment by eklatzer** [comment]
I will work on this one when #2279 is finished, so I can directly update the generator
