### ISSUE TITLE
Update track README

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2259]
Over the years, the track README become quite big with some large sections.

To make it easier to read, one suggestion would be to make each big section that is about a specific topic a separate .md file as a track docs file ([/docs](https://github.com/exercism/go/tree/main/docs)) and in the main README we can put links to those files. By making these sections into track docs, we also give them more visibility since they also appear in https://exercism.org/docs/tracks

A good example of a track that already does this beautifully is the [Python track](https://github.com/exercism/python).

/cc @BethanyG

**Comment by BethanyG** [comment]
@andrerfcsantos  @AshiishKarhade  -  I'm happy to help with this one as well, if you want to collaborate.  😄

**Comment by AshiishKarhade** [comment]
Yes @BethanyG , I would love to.

**Comment by andrerfcsantos** [comment]
@AshiishKarhade @BethanyG All yours! :)

Thank you both for the availability to work on this.

**Comment by AshiishKarhade** [comment]
@BethanyG Hi, This is my very start for open source contribution. I know little things and would expect your little help and guidance to work on this issue. Also, I am not very sure how does this work by collaborating. How do we go forward?

**Comment by BethanyG** [comment]
Hi @AshiishKarhade 😄 

Apologies for the slow response.  Got a bit buried with some work.  

I am happy to answer any questions I can for you.  This issue is mostly editing/writing in markdown that will display here on GitHub and exercism.org - so the bulk of the work is figuring out what information needs to stay in the README, what information should be moved into a track-specific CONTRIBUTING doc, and what if any other docs need to be created under `go/docs`. 

Before we go further, here are some exercism documentation links (_you don't have to read all of these, but there is useful information in them_):

**General Contributing Docs:**

- [Contributing to Exercism](https://exercism.org/docs/building) | [Exercism and GitHub](https://exercism.org/docs/building/github) | - [Contributor Pull Request Guide](https://exercism.org/docs/building/github/contributors-pull-request-guide)
-  [Code of Conduct](https://exercism.org/docs/using/legal/code-of-conduct) | [Being a Good Community Member](https://exercism.org/docs/community/being-a-good-community-member) | [The words that we use](https://exercism.org/docs/community/being-a-good-community-member/the-words-that-we-use)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide) | [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/product/tasks) | [Reputation](https://exercism.org/docs/using/product/reputation)  

Since you are brand-new, you are going to have some great insight into what kind of information is useful for someone coming to the repo for the first time, and what would be good to link to inside a README vs inside a CONTRIBUTING doc!

> _Also, I am not very sure how does this work by collaborating. How do we go forward?_

I've forked this repo and made a branch, `update-READEME-2259` where I have done a very crude first pass at dividing things up.  I have sent you a collaborator invite to my fork, so I think you can clone down the branch and make changes/pushes without issue.  As long as we both keep our local copies up-to-date, we can work on the files and push when needed.  Once we're happy with things, we can then do a PR to this repo for review, and the maintainers here will suggest/request improvements and merge when everything looks good.

It doesn't _have_ to be the way I've set it up -- I am very happy to collaborate with you in _your_ fork of this repo rather than mine.  We can also divide-and-conquer and each work on a separate doc (_for example, I can take the README and you can take the CONTRIBUTING_), should you want to do that instead.  Finally, I am also happy to have you do the work and I can just "consult"  😄  Just let me know what strategy you are most comfortable with.

**Comment by junedev** [comment]
@AshiishKarhade Are you still working on this?
