### ISSUE TITLE
Missing Test Case in Go exercise "Census"

### ISSUE THREAD

**Issue by kishannsangani** [exercism/go#2352]
[Census exercise in Go](https://exercism.org/tracks/go/exercises/census) has a task of completing the function `HasRequiredInfo` that validates if resident has all the required info. The test cases have empty address but doesn't have `nil` address. Shouldn't `nil` test case be a valid one?

**Comment by andrerfcsantos** [comment]
It should.

So the task here is to add one (or more) test cases where the `Address` field is `nil`.

**Comment by junedev** [comment]
You raise an interesting point here but probably a different one than you think.

A check like `if r.Address["street"] == ""` will never panic or something like that, even if Address was `nil` in the resident struct. Go always return the zero value of the type of the map values.

That means is probably no code that works for an empty map but fails for nil. Since the test cases are not shown to students for concept exercises, I am not sure there would be much value in adding the nil case. But we can do it if you prefer it.

In any case, there is something that should be fixed here. The exemplar solution (that is shown to mentors of the exercise) currently looks like this:
```
func (r *Resident) HasRequiredInfo() bool {
	if r.Name == "" {
		return false
	}

	if _, ok := r.Address["street"]; !ok {
		return false
	}

	if r.Address["street"] == "" {
		return false
	}

	return true
}
```
But that second if check is unnecessary as explained above, only having the third one is sufficient.

@kishannsangani Would you like to create a PR fixing the exemplar solution and optionally adding the test case?

**Comment by andrerfcsantos** [comment]
I still think the `r.Address == nil` test case has value. A student might initially only check for the `r.Address != nil` case thinking it is everything they need to check. But then if they look at the tests they see that the `nil` case is passing but not the test for `r.Address["street"]` being empty.

This also means that it's probably a good idea to have the `r.Address == nil` test case before the check for `r.Address["street"]` being empty, just so the tests are incremental.

**Comment by kishannsangani** [comment]
@andrerfcsantos, @junedev 

I assumed that the `nil` map might throw panic even during the read as well. But apparently, that is not the case. Yet, I will raise PR for `r.Address == nil` so that the tests are incremental.
