### ISSUE TITLE
Suggestion - Go Sylabus - Create a dependency between Ranged Iteration and Type Definition topics

### ISSUE THREAD

**Issue by rafacteixeira** [exercism/go#2446]
I got to a point where I could tackle the Ranged Iteration exercise or the Type Definition Exercise.

I took the ranged Iteration and had an issue because i needed a concept that would be taught by Type Definition

I'd like to suggest to put a strong dependency of completing Type Definition  before being able to access Ranged Iteration concepts.

thanks

**Comment by junedev** [comment]
@rafacteixeira I can't quite follow the issue here. It looks like there are two possible path in the syllabus tree but when you look more closely (i.e. open the concept) you will see that both concepts (type definitions and range iteration) are introduced by the same exercise "chessboard". That is why in the introduction text for the chessboard there is a section at the end about defining non-struct types so the student knows about this and is ready for the exercise.

**Comment by rafacteixeira** [comment]
it's not an issue. just a suggestion to make it more clear.
but i see your point. it is there and i didn't find it.
i'll close this suggestion.
