### ISSUE TITLE
Insufficent Information in Learning Exercise "The Farm"

### ISSUE THREAD

**Issue by saurabhmshr** [exercism/go#2477]
There's a lot of gap between the "Introduction" and "Instruction" sections.

In the "Introduction" section, only the first paragraph has information about interfaces. Everything else is about errors.
In the code block, `DivideFood` function receives an interface object and there is no information on this. This makes instructions tough to follow.

Unlike other exercises, multiple tasks are associated with the same function `DivideFood`. For this exercise, there should be two tasks at most - one for dividing food and the other for the silly nephew custom error.

**Comment by junedev** [comment]
I am also unhappy with the learning experience that the exercise provides, especially because the resulting code does not look very idiomatic.

But instead of trying even more small improvements, I am planning a more general restructering. Please see https://github.com/exercism/go/issues/2492. For now, I think the exercise is ok-ish to leave it like it is for a bit longer.

Since a new interfaces exercise will also mean an improved/ more detailed introduction for interfaces, I will close this issue in favor of https://github.com/exercism/go/issues/2492.
