### ISSUE TITLE
Prerequisites for exercises

### ISSUE THREAD

**Issue by unicormsatan** [exercism/go#2479]
I am a totally new to Go programming language and after learning on the python track I thought exercism would be the best and easiest way to learn Go.. But I have some issues with that.
After i joined the Go learning track just completing the hello world concept unlocked all the exercises. This was not the case with my python learning experience. It unlocked exercises as i completed the required prerequisites and it helped to try out what i learned by doing the exercise.
This is not a complain to the track maintainer to follow what the python track is like , it is my request as a new learner to make the learning experience more easier and more hands on.
so devs , track maintainers please consider adding prerequisites to the exercises it would make the learning much more easier and streamlined.
This is also my first time in GitHub , I am sorry for rant.

**Comment by junedev** [comment]
Thanks for reaching out. The reason the experience is different on the Go track is that we did not yet configure all the unlocking mechanism for the exercises. The open issue for this is here: https://github.com/exercism/go/issues/1396
This is a lot of work that nobody had time for yet. It also requires a lot of knowledge about the exercises and the concepts, so not something where we can easily ask the community for help.
Besides that, there are also some outstanding changes on the platform/website that we want to have implemented before adding this feature in Go.

Since we have that other issue to track the progress on this, I will close this one.
