### ISSUE TITLE
Triangle: type of Kind is forced to string

### ISSUE THREAD

**Issue by bupjae** [exercism/go#2504]
If Kind is not string, submitting got this error message:

    # triangle
    ./triangle_test.go:50:5: (*testing.common).Fatalf format %s has arg pair1.kind of wrong type triangle.Kind
    FAIL	triangle [build failed]
    '/usr/local/go/bin/go test --short --json .' returned exit code 2: exit status 2

It seems that recent change of `triangle_test.go` line 50 on https://github.com/exercism/go/pull/2469 causes this issue.

**Comment by andrerfcsantos** [comment]
Thanks for reporting this ❤️

The fix for this seems to require the change of `pair1.kind` to `pair1.name` on line 50 of [triangle_test.go](https://github.com/exercism/go/pull/2469/files#diff-a63edb1e3c7d930631d67a56cfb372f760c45614e15d4f27fcc2156928074e05).

While we're at it, I think it would be a good idea to make the error message clearer, instead of `"%s should not be equal to %s"`, something like `"the value of %s should not be equal to the value of %s"`.

Anyone is welcome to create a PR for this.
