### ISSUE TITLE
Categorize exercises directory

### ISSUE THREAD

**Issue by kpachhai** [exercism/go#726]
I came across this github project and found some awesome exercises to tackle for go beginners and experts alike. However, one thing I noticed was that the exercises directory is not very organized at the moment. It's pretty much a long never ending list. I love it but I was wondering if there's a way to categorize different types of exercises and organize them that way so it's easy for a novice like me to get to problems that I am most interested in. 
I was thinking more along the lines of:
1) Either create different directories under exercises like: beginner, intermediate, expert and then have the exercises in there OR
2) Maybe create different directories under exercises according to the types of problems they are.

Thoughts?

**Comment by robphoenix** [comment]
Hi @kpachhai, thanks, glad you're finding the exercises useful! 

Yes, you're right, the directory isn't organised. I like you're suggestions for improving this, however, this directory structure is deliberate. This repo is part of a larger project; [Exercism.io](http://exercism.io/), and the exercises are intended to be approached through the site. In the site you will unlock each exercise as you complete the previous one. You'll also be able to review and comment others solutions to the same exercises and receive feedback on your own solution. 
The site is soon to be updated also, with exercises grouped more according to topics. I'd recommend signing up to Exercism, with your Github account, as the best way of tackling these exercises. Otherwise you could refer to the [config.json file](https://github.com/exercism/go/blob/master/config.json), where you'll find some metadata for each exercise, such as a difficulty rating and a list of topics, which you might find useful.

If you're interested, we currently have an open issue, #345, to complete this metadata for all exercises, and we'd welcome any patches that improve the difficulty or topics of any exercise or update those that don't yet have this info. :smile: 

Thanks again, and however you choose to continue using these exercises, we're always open to suggestions like these! :tada:

**Comment by kpachhai** [comment]
@robphoenix Thanks for the quick reply. Totally gonna check out the site and go through exercises that way. And i'll check out that issue shortly.
