### ISSUE TITLE
Test case handling of empty slice returns

### ISSUE THREAD

**Issue by shaleh** [exercism/go#866]
Maybe this is me being a Go newbie.

    func something(.....) (result []type, err error) {
        if (predicate) {
            return
        }
    }

Lots of ellided things in that. My point is we have a function which has an early exit and so nothing is ever done to `result`. It is still an empty slice. [An issue on empty v. nil slices](https://github.com/golang/go/issues/4133) has a conversation about what is happening.

As far as Go is concerned a nil slice and an empty slice function the same. This [playground](https://play.golang.org/p/3t9Ez3P7ST) documents this. However in many if not all of the tests in this series the test fails on nil slices. This leads to really confusing error messages:

    expected [], actual []

Yuck!!

Could `reflect.DeepEqual` be wrapped in something that either a) complains about nil or b) handles them better? Help the newbies out :-)

**Comment by robphoenix** [comment]
You're right that is a confusing error message. I think though we could handle it with different formatting, using `%#v` rather than `%v`: https://play.golang.org/p/U8XPCbm9Zz

There was a similar issue previously: https://github.com/exercism/go/issues/414

Can you specify which exercises you've experienced this with and we can fix them so the output is friendlier.

**Comment by shaleh** [comment]
Pretty much every exercise where you are expected to return a slice. I would often write code like this:

    func something(input string) (result []type, err error) {
        if input == "" {
            return
        }

        value := compute(......)
        result = append(result, value)
        return
    }

Which is 100% correct but would fail the tests. So I would have to update my early returns to be `[]type{}, nil`. Which works but gets annoying.

I bumped into this most recently on the change exercise. 0 change, empty list. Bzzzt!

**Comment by robphoenix** [comment]
> So I would have to update my early returns to be []type{}, nil. Which works but gets annoying.

I'm not sure I understand why you would have to do this?

I believe naked returns are not recommended as idiomatic Go.

```
func something(input string) ([]type, error) {
    var result []type
    if input == "" {
        return result, error
    }

    value := compute(......)
    result, err = append(result, value)
    return result, error
}
```

Though this returns the same nil slice that you describe as failing the tests. To return an empty slice you would create the result var as so `result := []type{}` instead.

I'm not sure I fully understand the issue with the code above. Otherwise I think this can be fixed with better formatting.

**Comment by shaleh** [comment]
Right. There is no reason that here https://github.com/exercism/go/blob/master/exercises/prime-factors/example.go#L6 the programmer needs to explicitly empty the slice. It starts off empty. Those {} exist solely to appease the unit tests.

**Comment by robphoenix** [comment]
I understand. I wonder if this https://github.com/exercism/go/blob/master/exercises/prime-factors/prime_factors_test.go#L16 should be `nil` rather than `[]int64{}`. I haven't thought on this much, so the answer may be obvious.

**Comment by shaleh** [comment]
This is code from the `bytes` packages:

    // TrimLeftFunc returns a subslice of s by slicing off all leading UTF-8-encoded
    // Unicode code points c that satisfy f(c).
    func TrimLeftFunc(s []byte, f func(r rune) bool) []byte {
        i := indexFunc(s, f, false)
        if i == -1 {
                return nil
        }
        return s[i:]
    }

**Comment by robphoenix** [comment]
> Right. There is no reason that here /exercises/prime-factors/example.go@master#L6 the programmer needs to explicitly empty the slice. It starts off empty. Those {} exist solely to appease the unit tests.

I think it's reasonable for the unit tests to expect an empty slice rather than a nil slice, this goes for the `change` exercise also. And in other circumstances it may be better to expect a nil slice. In each circumstance we have to write the code that passes the unit tests. I don't think we should be changing unit tests because it can be annoying to write the code needed to make them pass.

If there are particular test cases that expect an empty slice where a nil slice is more appropriate we can look at changing those. 
I believe the formatting of test cases that expect an empty slice or a nil slice can be improved if needs be to make the distinction between an empty slice and a nil slice more apparent. Here we can use either `%q` or `%#v` instead of `%v`. I think we should have caught all these by now. :crossed_fingers:

**Comment by robphoenix** [comment]
Unless you think there's more to cover here @shaleh I believe this can be closed.

**Comment by shaleh** [comment]
Ack

On October 16, 2017 2:29:01 AM PDT, Rob Phoenix <notifications@github.com> wrote:
>Unless you think there's more to cover here @shaleh I believe this can
>be closed.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/go/issues/866#issuecomment-336831753

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
