### ISSUE TITLE
Keeping nextercism branch in sync with master

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#893]
In #887 @tleen [asked](https://github.com/exercism/go/pull/887#issuecomment-334768679)

> I wonder if we should be merging/rebasing nextercism against master periodically?

I think we have to merge `master` branch into `nextercism`, creating a merge commit. Thus when we merge `nextercism` back into `master` it will look like [this](https://github.com/robphoenix/exercism-go/commits/master-copy).

If we rebase `nextercism` on `master` then we have to force push, which will cause the branch to look like [this](https://github.com/robphoenix/exercism-go/commits/nextercism-copy), note how I am now attached to commits I had nothing to do with.

I only use git as part of a team workflow in this repo, which is to say I am an amateur searching for answers on the internet. Is there a better way?

**Comment by tleen** [comment]
Unsure, both look sub-optimal. Will have to research. For now I suppose we can just try to keep master as untouched as possible so the final mega-merge won't be too bad?

**Comment by ferhatelmas** [comment]
I had said yes for rebase to mean that changes in master must be incorporated into nextercism.

However, rebase will create problems if multiple people are working on a branch so I'm for merging.

**Comment by ferhatelmas** [comment]
IMHO, we should get going with merge strategy because it apparently creates some barriers for contributors.

**Comment by tleen** [comment]
I think we should start merging this sooner rather than later. `nextercism` is still a ways out and having both branches is really complicating things, especially for the new submitters.

IIRC the issue with updating config against `master` was that it re-ordered the track. I think if we restructure `config.json` in `nextercism` to reflect the ordering in `master`'s version we should be ok?

**Comment by ferhatelmas** [comment]
I agree. 

One misleading case I see is that we might have the exercise implemented in `nextercism` but [website](http://exercism.io/languages/go/todo) shows it as unimplemented. Contributors implement it and send PR then they realize there is a branch we're working on and exercise is already there.

If you want to do it, go ahead. Otherwise, let me know and I will give a try until tomorrow.
