### ISSUE TITLE
How to keep generated tests up-to-date ?

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#967]
Right now, it's done manually once in a while like in #966. However, it needs to be automated.

I don't know how it is handled in other tracks so first I think we should check existing solutions.

However, two options from top of my head:
* a bot listens problem specifications and runs generators; upon change, sends a PR
* CI runs them and fails if update is required

**Comment by tleen** [comment]
It is something we can raise for track maintainers. May even belong in the Exercism tool suite somewhere.

**Comment by bitfield** [comment]
My sense is that `problem-specifications` is updated pretty regularly, so perhaps just having a human being run `run-generators` every week or two would be sufficient? If there are changes, which there probably will be, the human can open a PR. I'd rather see a single PR that brings _all_ exercises up to date every so often, than a flood of automated PRs, one for every upstream change.

Doing this in CI is a good idea, but something seems wrong to me about rejecting a perfectly good PR just because the upstream specs have changed. That would then require an extra commit on the PR to update the tests, which would have nothing to do with the actual purpose of the PR.

Perhaps someone else can think of a better way to automate this, but failing that, I suggest we close this.

**Comment by kytrinyx** [comment]
@bitfield I think someone manually running a script every couple of weeks sounds like a perfectly reasonable approach to this for now!
